### ISSUE TITLE
#1 User can view app info

### ISSUE THREAD

**Issue by KiannaBrandt** [KiannaBrandt/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view the application's information.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the home page loads, the user will be able to see a short description and links to sign up.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-08-26 at 9 32 36 PM](https://user-images.githubusercontent.com/69865999/131072633-fe36be4e-9d31-41ae-b109-477b8556ca37.png)
![Screen Shot 2021-08-26 at 9 32 15 PM](https://user-images.githubusercontent.com/69865999/131072634-d7d82ff4-d56c-40f5-bdb9-f6bb3d36c93a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create Home Component
- [x] Create a navbar with the name of the application
- [x] Add links to the desktop navbar for prices, sign in, and signup
- [x] Add links to the mobile navbar for sign up and menu icon
- [x] Create an expanded menu for mobile
- [x] Add links to the mobile expanded menu for prices, sign up, and sign in

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
