### ISSUE TITLE
#2 User can create account

### ISSUE THREAD

**Issue by KiannaBrandt** [KiannaBrandt/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to enter in their personal details to create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on any of the sign up options, they will be able to fill out a form with their personal details to create an account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-08-12 at 7 04 25 PM](https://user-images.githubusercontent.com/69865999/129294732-f99b953b-1c4e-47a4-b30d-37b019853c39.png)
![Screen Shot 2021-08-12 at 7 04 38 PM](https://user-images.githubusercontent.com/69865999/129294734-1456015e-1d42-4ff4-a807-6a48b25d6cd2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to create initial database
- [ ] Update `data.sql` to create a dummy user 

### ☁️ Server

- [ ] Add POST /api/auth/sign-up 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Listen for `'click'`events on the sign up options
- [ ] If a sign up option is clicked show the Create an account page
- [ ] Create a form with the following fields: first name, last name, email address, password
- [ ] Make all form inputs `required`
- [ ] Listen for `'submit'` events on the form
- [ ] Store new user info in the `"users"` table

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
